# Ratul Chakraborty
# BDA 2nd Sem

In [1]:
import numpy as np
import pandas as pd

# Problem 1

In [2]:
a = int(input("Enter a: "))
b = int(input("Enter b: "))
n = int(input("Enter n: "))
arr = np.random.randint(a, b, n, dtype = np.int64)
arr

Enter a: 10
Enter b: 100
Enter n: 30


array([23, 91, 21, 33, 47, 90, 39, 87, 40, 55, 36, 63, 56, 49, 60, 70, 85,
       65, 69, 37, 75, 75, 59, 15, 62, 81, 80, 27, 33, 38], dtype=int64)

In [3]:
epsilon = np.finfo(float).eps; epsilon

2.220446049250313e-16

In [4]:
epsilon.dtype

dtype('float64')

In [5]:
ar = np.random.randint(10**12, 10**13, n, dtype = np.int64)*epsilon*(10**4)
ar

array([ 7.33528109, 10.21096637,  2.50580918,  5.53232414,  9.62416072,
        2.22457498, 19.50882211, 14.54663778, 17.43491188, 21.94224517,
       16.880325  , 12.76951426, 17.46422213, 11.30855081,  6.46580963,
        4.09625833, 21.75653718,  3.75462796, 16.95885785, 13.2692141 ,
        3.38404663, 19.14497695, 20.09125849, 15.59404866, 18.31340385,
       11.3024492 , 16.98489428,  4.46760526,  2.94264311,  6.54421813])

In [6]:
floats = arr + ar; floats

array([ 30.33528109, 101.21096637,  23.50580918,  38.53232414,
        56.62416072,  92.22457498,  58.50882211, 101.54663778,
        57.43491188,  76.94224517,  52.880325  ,  75.76951426,
        73.46422213,  60.30855081,  66.46580963,  74.09625833,
       106.75653718,  68.75462796,  85.95885785,  50.2692141 ,
        78.38404663,  94.14497695,  79.09125849,  30.59404866,
        80.31340385,  92.3024492 ,  96.98489428,  31.46760526,
        35.94264311,  44.54421813])

### Unsorted and Sorted Sum

In [7]:
sort_sum = sum(np.sort(floats))
unsort_sum = sum(floats)

In [8]:
# Error
unsort_sum - sort_sum

4.547473508864641e-13

### Compensated and Sorted Sum

In [9]:
compen_sum = 0
y = 0
for i in range(n):
    z = y+floats[i]
    w = compen_sum + z
    y = compen_sum - w + z
    compen_sum = w
compen_sum

2015.3591952511993

In [10]:
# Error
compen_sum - sort_sum

4.547473508864641e-13

### Unsorted and Compensated Sum

In [11]:
unsort_sum - compen_sum

0.0

# Problem 2

In [17]:
c = int(input("Principal Amount: "))
i = int(input("Interest rate: "))
n = 365
x = i/n

Principal Amount: 1000
Interest rate: 7


### Simple Compound Inerest

In [18]:
compound_simple = c*((1+x)**n - 1)/x
compound_simple

53462465.90670795

### Compound Interest through log(1+x) function

In [19]:
compound_given = c*(np.exp(n*((x*np.log(1+x))/((1+x)-1)))-1)/x
compound_given

53462465.90670736

### Compound Interest through Maclaurin Series

In [20]:
mac = 0
for i in range(1, 366):
    mac += (-1)**(i+1)*(x**i)/i
    
compound_mac = c*(np.exp(n*mac)-1)/x
compound_mac

53462465.906707406

# END